name: Benchmark
on: push

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      session_cookie: ${{ secrets.session_cookie }}

    defaults:
      run:
        working-directory: ./2023 Elixir

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          version-file: ./2023 Elixir/.tool-versions
          version-type: strict

      - name: Setup
        run: mix do deps.get, compile

      - name: Benchmark Part 1
        run: mix d11.p1 -b

      - name: Benchmark Part 2
        run: mix d11.p2 -b
